Traceback (most recent call last):
  File "exo2.py", line 14, in <module>
    total_points = int(sys.argv[1])
IndexError: list index out of range
